// <auto-generated />
using System;
using Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251102191743_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7be2cea-9450-47ce-b47c-2765db336eb1"),
                            Email = "user@gmail.com",
                            FirstName = "User1 LastName",
                            LastName = "User1 Lastname",
                            PasswordHash = "AQAAAAIAAYagAAAAEJtnVaDv1S4qlEXx1npQMw46zdqk9ffwKhUdeMIVZbOMcZPQ4fhkOn1BmzjKVV+79A==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("dfa86cdf-de8a-469a-801d-eda786b908b6"),
                            Email = "user2@gmail.com",
                            FirstName = "User2 LastName",
                            LastName = "User2 Lastname",
                            PasswordHash = "AQAAAAIAAYagAAAAEE5Ghw4I+CNGzhnLBuxGjNd31hCoJhPVbAldgwEuDR+8txFzStAdmlifNcImm6tJdQ==",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("c9336243-d5bd-46f3-8b8f-cc754afbc398"),
                            Email = "user3@gmail.com",
                            FirstName = "User3 LastName",
                            LastName = "User3 Lastname",
                            PasswordHash = "AQAAAAIAAYagAAAAEEGYGA/9/8GlcunfYl7L4pC2YZ6t70pU9zoMhp8x4D3BT8yfalIPYP8cnI3jvHCzbw==",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
