// <auto-generated />
using System;
using Identity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Identity.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Identity.Domain.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7be2cea-9450-47ce-b47c-2765db336eb1"),
                            Email = "user@gmail.com",
                            FirstName = "User1 LastName",
                            LastName = "User1 Lastname",
                            PasswordHash = "AQAAAAIAAYagAAAAEOgm3hO3Iw42LvL7Oz0GDaPpHIyi5Luk1qxrFwvFot+fMVW3RsKb9budLYq2h1yx7Q==",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = new Guid("dfa86cdf-de8a-469a-801d-eda786b908b6"),
                            Email = "user2@gmail.com",
                            FirstName = "User2 LastName",
                            LastName = "User2 Lastname",
                            PasswordHash = "AQAAAAIAAYagAAAAEEuqy+k25QmeoyCc3HtlY640H/tpv7uJoiNAfqOX9EN8LVdOjGSmFdp9JJtru8mjbg==",
                            Role = "User"
                        },
                        new
                        {
                            Id = new Guid("c9336243-d5bd-46f3-8b8f-cc754afbc398"),
                            Email = "user3@gmail.com",
                            FirstName = "User3 LastName",
                            LastName = "User3 Lastname",
                            PasswordHash = "AQAAAAIAAYagAAAAEClk2HrEYI+xitJhIdqQSwwYzTtVSYuomNHaGlghbPINTbtYs+YWQL+92apPJq7znw==",
                            Role = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
